repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: mixed-line-ending

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.9
    hooks:
    -   id: remove-tabs

-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        types: [python]
        language_version: python3.8
        args: ['-l79']

-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.8.3'
    hooks:
    -   id: flake8
        additional_dependencies:
        -   flake8-print
        args: ['--config=.flake8']

-   repo: local
    hooks:
    -   id: pypi-package
        name: create package
        entry: /usr/local/bin/python3.8 setup.py sdist bdist_wheel
        language: system
        always_run: true
        pass_filenames: false
        stages: [push]

    -   id: twine
        name: upload package
        entry: bash -c 'twine upload --username sgsunder --password ${TWINE_PASSWORD} --skip-existing --non-interactive dist/*'
        language: system
        always_run: true
        pass_filenames: false
        stages: [push]

fail_fast: true
exclude: LICENSE.md
